name: aoxel_decoder
description: A starting point for Dart libraries For Decoding the Aox Audio Files.
version: 1.0.0
repository: https://github.com/cyberkutti-iedc/aoxel-Dart
#author: SREERAJ V RAJESH
maintainers: Sreeraj V Rajesh <cyberkutti@gmail.com>
homepage: https://github.com/cyberkutti-iedc/aoxel-Dart
environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  logger: ^2.0.2+1
  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
